### ISSUE TITLE
useSignalEffect won't fire.

### ISSUE THREAD

**Issue by saurabswaarm** [luisherranz/deepsignal#67] opened 2024-08-30 10:33 UTC
I'm unable to get use signal effect to fire in my **React Application** if I follow the following set up.(`adjRow` is the deep signal.)

<br>

```
useSignalEffect(()=>{
    if(finalTableRows.length > 0 && adjRow.action=== 'adding'){
      // some code here
      adjRow.reset();
    }
  })
  ```

However I can get the useSignalEffect to fire if instead I assign adjRow.action to a variable.

```
useSignalEffect(()=>{
    const action = adjRow.action 
    debugger;
    if(finalTableRows.length > 0 && action=== 'adding'){
     // some code here
      adjRow.reset();
    }
  })
  ```
  
  is this something to do with the way signals / reactivity works ?
  
  Please not i am using / have tried babel transform and the useSignals hook to wire my react appication in.
  
  
<hr>
### Versions

 - react - 18.3.1 <br>
 - @preact/signals-react - 2.2.0 <br>
 - deepsignal - 1.5.0 <br>

**Comment by luisherranz** [comment] 2024-08-30 10:43
Could you please reproduce the error using StackBlitz so I can take a look? You can fork [this template](https://stackblitz.com/edit/vitejs-vite-zoh464?file=src%2Fmain.jsx) to get started.

**Comment by saurabswaarm** [comment] 2024-08-30 11:52
Hi, here's the code, but it seems to work fine. I can access the signal without having an assignment operator. I can't reproduce my error means it has something to do with my set up.

https://stackblitz.com/edit/vitejs-vite-cyswtz?file=src%2Fmain.jsx

But in my codebase we are using webpack and babel also in the babel trasform i have set it to `manual`,

```
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ],
    "plugins": [
        ["@babel/transform-runtime", {
          "regenerator": true
        }],
        ["module:@preact/signals-react-transform", {
          "mode":"manual"
        }]
      ]
}
```



 as `auto` gives me this error

```
 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component.
 ```

**Comment by saurabswaarm** [comment] 2024-08-30 16:00
now that i test it out with just preact, it happens with preact too. Doesn't matter if I use the useSignals hook or if i annotate my components like
<br>
```
/**
 * @useSignals
 */
const Component = (props) => {
```
<br>

More info.
"webpack": "^5.51.1",
"webpack-cli": "^4.7.2",
"webpack-dev-server": "^3.11.2"
"babel-loader": "^8.2.2",
"@babel/core": "^7.15.0",
  
  Another interesting observation is our node is locked in at v14.
  
  I think I'll file an issue over at preact as well. We can close this because this is clearly not an issue with deep signals.

**Comment by luisherranz** [comment] 2024-09-01 08:37
> We can close this because this is clearly not an issue with deep signals.

Alright, I'll close it then. Feel free to reopen it if you find that the issue is indeed related to deepsignal.

**Closed by luisherranz** 2024-09-01 08:37 UTC
