### ISSUE TITLE
Support for @preact/signals-react with DeepSignals

### ISSUE THREAD

**Issue by Sumit2202** [luisherranz/deepsignal#8] opened 2023-01-17 19:06 UTC
I am using @preact/signals-react with react-native and it works but in many places I have a deeply nested object, to which I need to listen to property changes and re-render accordingly.
DeepSignals with @preact/signals-react would be the ideal solution.

**Comment by luisherranz** [comment] 2023-01-18 08:22
Can you test if this works?

```js
import "@preact/signals-react"
import { deepSignal } from "deepsignal/core";

// ...
```

**Comment by Sumit2202** [comment] 2023-01-19 15:23
It did not work, here is the [stackblitz](https://stackblitz.com/edit/react-ts-fxhybh?file=App.tsx)

**Comment by luisherranz** [comment] 2023-01-21 12:13
It's working fine using Vite: https://stackblitz.com/edit/vitejs-vite-arvs9j?file=src%2Fmain.tsx

The error `Cannot use import statement outside a module` doesn't seem related to using `deepsignal` in React, but to the bundling.

**Comment by luisherranz** [comment] 2023-01-21 12:14
Closing as it works fine with React. I'll investigate the import issue, though.

**Closed by luisherranz** 2023-01-21 12:14 UTC

**Comment by luisherranz** [comment] 2023-01-22 10:51
I'm unable to reproduce the problem locally. If I download the Stackblitz project and run it locally, there is no `import` error.

It works fine using CRA locally or in [Codesandbox](https://codesandbox.io/s/deepsignal-with-cra-q8jzcg), and it works fine using [Vite in Stackblitz](https://stackblitz.com/edit/vitejs-vite-arvs9j) 🤷‍♂️ 

Could you please update to `1.1.3` and check if it works on your project?
